set(CURRENT_LIB_PATH ${CMAKE_CURRENT_LIST_DIR})
cmake_print_variables(CURRENT_LIB_PATH)
set(OPENSSL_INCLUDE_DIR ${CURRENT_LIB_PATH}/include/)

INCLUDE_DIRECTORIES(${OPENSSL_INCLUDE_DIR})

find_library(SSL_LIBRARY NAMES libssl.a PATHS ${CURRENT_LIB_PATH}/lib REQUIRED)
add_library(ssl STATIC IMPORTED GLOBAL)
set_target_properties(ssl PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}"
        IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
        IMPORTED_LOCATION "${SSL_LIBRARY}"
        )

find_library(CRYPTO_LIBRARY NAMES libcrypto.a PATHS ${CURRENT_LIB_PATH}/lib REQUIRED)
add_library(crypto STATIC IMPORTED GLOBAL)
set_target_properties(crypto PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}"
        IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
        IMPORTED_LOCATION "${CRYPTO_LIBRARY}"
        )