set(CURRENT_LIB_PATH ${CMAKE_CURRENT_LIST_DIR})
cmake_print_variables(CURRENT_LIB_PATH)
set(GFLAGS_INCLUDE_DIR ${CURRENT_LIB_PATH}/include/)

INCLUDE_DIRECTORIES(${GFLAGS_INCLUDE_DIR})

find_library(GFLAGS_LIBRARY NAMES libgflags.a PATHS ${CURRENT_LIB_PATH}/lib REQUIRED)

add_library(gflags STATIC IMPORTED GLOBAL)
set_target_properties(gflags PROPERTIES
        INTERFACE_COMPILE_DEFINITIONS "GFLAGS_IS_A_DLL=0"
        INTERFACE_INCLUDE_DIRECTORIES "${GFLAGS_INCLUDE_DIR}"
        IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
        IMPORTED_LOCATION "${GFLAGS_LIBRARY}"
        )
