set(CURRENT_LIB_PATH ${CMAKE_CURRENT_LIST_DIR})
cmake_print_variables(CURRENT_LIB_PATH)
set(ZSTD_INCLUDE_DIR ${CURRENT_LIB_PATH}/include/)

INCLUDE_DIRECTORIES(${ZSTD_INCLUDE_DIR})

add_library(zstd STATIC IMPORTED GLOBAL)
set_target_properties(zstd PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${ZSTD_INCLUDE_DIR}"
        IMPORTED_LOCATION "${CURRENT_LIB_PATH}/lib/libzstd.a"
        )
