set(CURRENT_LIB_PATH ${CMAKE_CURRENT_LIST_DIR})
cmake_print_variables(CURRENT_LIB_PATH)
set(lz4_INCLUDE_DIR ${CURRENT_LIB_PATH}/include/)
INCLUDE_DIRECTORIES(${lz4_INCLUDE_DIR})

find_library(lz4_LIBRARIES NAMES liblz4.a PATHS ${CURRENT_LIB_PATH}/lib REQUIRED)


add_library(lz4 STATIC IMPORTED GLOBAL)
set_target_properties(lz4 PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${lz4_INCLUDE_DIR}"
        IMPORTED_LOCATION "${lz4_LIBRARIES}"
        )
